# Generated by Django 4.0.5 on 2022-11-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='favourite',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
