# Generated by Django 4.0.5 on 2022-11-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orderitem_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favourite',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
